# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c56c270de4ed839bdb0d419db6f52278858e5643e3a30e08338eaeb158de632de009d1b7a4c32d4370925b892de7c05f4bc9cfc246ca68cbbaa68558bf98da7

test:
  secret_key_base: a5516dc35df1af85682817d8e695ba3d3483b6ae0671ace5368662c4d1527b3f71b3dde0b732bf3e3145dec090e49cf9bc73ecbf87f5607eb035137c6db69eb7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
